import Head from "next/head";
import Form from "@/components/Form";
import LinkCreated from "@/components/LinkCreated";
import { useState } from "react";

export default function Home() {
  const [serverRes, setserverRes] = useState(null);

  const getServerResponse = (res: any) => setserverRes(res);
  return (
    <>
      <Head>
        <title>URL shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/iconShort.png" />
      </Head>
      <main>
        <Form response={getServerResponse} />
        <LinkCreated linkProp={serverRes} />
      </main>
    </>
  );
}
